"""empty message

Revision ID: 64857a565e39
Revises: 3c924c68325a
Create Date: 2022-04-16 19:54:06.403242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64857a565e39'
down_revision = '3c924c68325a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'photo')
    # ### end Alembic commands ###
