"""empty message

Revision ID: 744eecaa1b7a
Revises: a79b22194b07
Create Date: 2022-04-25 02:42:58.742906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744eecaa1b7a'
down_revision = 'a79b22194b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('bikeModel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_us', 'bikeModel')
    # ### end Alembic commands ###
