"""empty message

Revision ID: d1b35702fb0a
Revises: 5fa4dfd706f4
Create Date: 2022-04-19 22:07:11.419539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b35702fb0a'
down_revision = '5fa4dfd706f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_us', 'message')
    # ### end Alembic commands ###
